### ISSUE TITLE
Question on setting up system id / interface with QGroundControl

### ISSUE THREAD

**Issue by edrdo** [gmyoungblood-parc/docker-alpine-ardupilot#1]
Hi,

I've been testing your docker container on MacOs. Good job!

I'm a rookie concerning the use of Ardupilot/MAVLink related tools, and I am having trouble setting two SITL instances simultaneously in interface with QGroundControl. I'm not sure if the problem lies with the SIM_OPTIONS I use per each container or with QGroundControl:

1) For instance 1 I use 

`docker run --rm -it -e "SIM_OPTIONS=--out=udpout:docker.for.mac.localhost:14550" gmyoungbloodparc/ardupilot-sitl`

2) For instance 2 I use

`docker run --rm -it -e SIM_OPTIONS="--out=udpout:docker.for.mac.localhost:14551 -m --target-system=7" gmyoungbloodparc/ardupilot-sitl`

3) QGroundControl is configured to listen via UDP both on ports 14550 (for instance 1) and 14551 (for instance 2). Not sure if this is necessary, anyway the target system id is set to 7 in the second instance, to make the GCS differentiate between both.  

QGroundControl gets confused, it only sees one of the planes, and the state flickers between one and the other. Is this a QGroundControl configuration problem or do I need to supply further settings to the container instances? 

Best, 
Eduardo

**Comment by edrdo** [comment]
Hi,

Just a followup, as I managed to solve the problem.

The MAVLink "--target-system" option had no effect. After some googling, I found that the SYSID_THISMAV simulator parameter is the real culprit. This can be changed through the MAVLink command line in the container, but that is not a very convenient option for an automated startup. I found no way to alter the parameter through the command line / SIM_OPTIONS environment variable - is there one?

The workaround was changing the container entry point such that it runs a script (in an host volume) that adds SYSID_THISMAV=DESIRED_SYS_ID to the default parameterisation. 

```
#! /bin/bash
source /etc/profile
echo SYSID_THISMAV=$1 >> /ardupilot/Tools/autotest/default_params/plane.parm
sim_vehicle.py --speedup=$SPEEDUP $SIM_OPTIONS
```

The docker command was 

`docker run --rm -it -v $PATH_FOR_MY_SCRIPT:/external -e "SIM_OPTIONS=--out=udpout:docker.for.mac.localhost:14550" --entrypoint "/external/MY_SCRIPT.sh" gmyoungbloodparc/ardupilot-sitl $DESIRED_SYS_ID`

Maybe there's a simpler way to do this? (Well, anyway, it's now working for me.)

Best,
Eduardo

**Comment by gmyoungblood** [comment]
Glad you were able to get it to work for you. If you have any suggestions on a fix that will work for everyone, you are welcome to make a pull request.

Cheers,
Michael

**Comment by edrdo** [comment]
Thanks, I'll make a pull request, guess it may be helpful to other people. 

Best,
Eduardo

**Comment by gmyoungblood-parc** [comment]
Hi Eduardo,

Thank you for your contribution to the project. Did you want to write a README.md for the scripts directory to help users know how to use them?

Thanks,
Michael

**Comment by edrdo** [comment]
Sure, I'll make another PR then.

Best,
Eduardo
